### ISSUE TITLE
Stworzenie cubita od zarządzania biblioteką zapisanych planów

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#30]
Stanem będzie zbiór unikalnych obiektów Schedule. Cubit ten musi pozwalać na dodanie i usuwanie obiektów. Stan tego cubita musi być persistent czyli zapisywany do pamięci urządzenia (Zrób na wzór cubita settings).

**Comment by ThePhaseless** [comment]
Będzie naprawione w #29
