### ISSUE TITLE
Dodanie zmiany typu motyw (ThemeType) do cubita Settings

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#31]
Sprawa wygląda identycznie jak ze zmianą ThemeMode w tym samym cubicie, więc możesz zrobić tak samo. 
W main.dart użyj tej nowej właściwości by była przekazywana do funkcji getTheme(…)
Pamiętaj, że cubit settings jest zapisywany do pamięci i Hive potrzebuje adaptera dla typu ThemeType. Sprawa wygląda identycznie jak z ThemeModeAdapter, więc utwórz ThemeTypeAdapter i go zarejestuj w register_adapters.dart

**Comment by ThePhaseless** [comment]
@mpygruu możesz jeszcze spróbować wykombinować jak przechowywać czy motyw jest wybranym kolorem, kolorem retro albo dynamicznym z systemu

**Comment by matyjb** [comment]
@ThePhaseless dojdziemy do tego. Niech najpierw zrobi to co jest w tasku
