### ISSUE TITLE
Dynamiczny kolor motywu

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#36]
W SettingsCubit trzeba dodać nową właściwość `systemColor`, która będzie przechowywać aktualny kolor systemowy. Przy inicjalizacji SettingsCubit trzeba ustawić go na odpowiedni kolor używając jakiejś metody z pakietu `dynamic_color`. 

Dodatkowy problem jaki trzeba rozwiązać:
Pakiet dynamic_color odpytuje system o kolor na żądanie. Chcemy by apka zareagowała jeśli user zmieni kolor w ustawieniach systemu. Pomysł mam taki by użyć [WidgetsBindingObserver](https://stackoverflow.com/questions/51835039/how-do-i-check-if-the-flutter-application-is-in-the-foreground-or-not) i wykorzystać fakt, że user musi wyjść z apki by ten kolor zmienić. Możemy to wykryć i przy `AppLifecycleState.resumed` uruchomić metodę odświerzającą systemColor w SettingsCubit

**Comment by mpygruu** [comment]
Spróbuję zrobić jutro.

**Comment by ThePhaseless** [comment]
już zrobiłem przy okazji #41
