### ISSUE TITLE
Providery oraz repozytoria danych

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#40]
Stworzyć klasę `SggwHubApi` w folderze `data/providers` z metodami wysyłającymi zapytania do api i zwracające `Future<Response>`. Użyj pakietu dio.

Endpointy, które nas interesują:
- GET /api/Lecturers
- GET /api/Schedules
- GET /api/Schedules/{scheduleId}
- GET /api/Lecturers/{lecturerId}/schedule/full

Następnie stwórz klasę SggwHubRepo w folderze `data/repositories`, która korzysta z jednej instancji SggwHubApi, mapuje otrzymane dane z api na obiekty i udostępnia metody:
- Lista wszystkich prowadzących (returnuje `Future<List<LecturerBase>>`)
- Lista wszystkich planów (returnuje `Future<List<ScheduleBase>>`)
- Plan zajęć dla planu o danym id (returnuje `Future<Schedule>`) *tu się jeszcze zmieni endpoint ale finalnie powinien być obiekt Schedule
- Plan zajęć dla prowadzącego o danym id (returnuje `Future<Lecturer>`)

Modele danych są już gotowe na `dev`. Nie trzeba robić testów (front nie jest od testowania backendu)

**Comment by mpygruu** [comment]
Zrobię. Przysiądę do tego jutro wieczór i w sobotę do zwycięstwa

**Comment by mpygruu** [comment]
Czy foldery providers i repositories mają być w folderze models tak jak napisane czy chodziło o folder data?

**Comment by matyjb** [comment]
A rzeczywiście. W data mają być. Edytuje posta oryginalnego
