### ISSUE TITLE
Ekran ustawień

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#41]
Dokończyć ekran ustawień. Powinien mieć:
- Zmiana motywu (te dwa switche)
- Zmiana języka (pl, eng)
- Guzik przenoszący do zarządzania powiadomieniami (niech nic nie robi ten guzik jak na razie)
- Guzik od ukrycie fab’a od filtrów na głównym ekranie (niech nic nie robi ten guzik jak na razie)
- Guzik pokazania modalu zapisanych planów (niech nic nie robi ten guzik jak na razie)
- About app (zrobić na wzór obecnej apki, użyj [showAboutDialog()](https://www.youtube.com/watch?v=YFCSODyFxbE))
- Privacy policy (guzik z [launchUrl](https://pub.dev/packages/url_launcher), niech link prowadzi [tutaj](https://silvernetgroup.github.io/privacy-policy/))
- Włączanie trybu debug po kliknięciu 7 razy w logo apki na dialogu about app (tak jak jest teraz). Inspirowane trybem programisty z androida

**Comment by ThePhaseless** [comment]
Zaklepuje

**Comment by ThePhaseless** [comment]
@bionicl prośba, sprawdzisz czy na iphonie się odpala jak naciśniesz privacy policy? Na androidzie musiałem dodawać intent do manifestu
