### ISSUE TITLE
Ekran powitalny

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#44]
Widget ekranu powitalnego prezentujący funkcje apki:
- Przeglądanie planów zajęć dla studenta oraz prowadzącego zajęcia
- Powiadomienia o zmianach w zapisanych planach. Możliwość wyłączania/włączania ich w ustawieniach
- Budzik/powiadomienie (tu jeszcze trzeba to ustalić, chyba budzik byłby lepszy) o nadchodzących zajęciach (np. 10 minut przed zajęciami)
- Odnajdowanie sali na mapie
- Różne motywy

Proponuje prezentacje w stylu karuzeli

**Comment by mpygruu** [comment]
Dodałem na figmie swoją propozycję @matyjb @ThePhaseless
