### ISSUE TITLE
Light mode retro theme

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#53]
Coś jest nie tak z kolorkami w motywie retro dla jasnego motywu. Sam motyw ustawia się dobrze, ale dla:
- ThemeMode.dark, ThemeType.retro => kolorki są ok
- ThemeMode.light, ThemeType.retro => kolor tekstu zmienia się na czarny, ale pozostałe kolory są jak dla typu ciemnego

**Comment by ThePhaseless** [comment]
Tak, bo kolory są ustawione które mi się udało "skopiować", dla jasnego motywu nie robiłem, ale brightness się zmienił, więc kolor czcionki również, bo go nie zmieniałem w żadnym colorScheme

**Comment by matyjb** [comment]
No to trzeba dorobić
