### ISSUE TITLE
Bug ze zmianą języka

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#58]
Widgety na ekranie ustawień się nie rebuildują po zmianie języka (oprócz tile'a od zmiany języka o dziwo). 
![chrome_JPIhPH9ogC](https://github.com/SilverNETGroupSGGW/psggw/assets/19827704/7d0c9146-9aa7-4a6e-9655-eeb909ae4343)

**Comment by mpygruu** [comment]
o właśnie dokładnie to wyczaiłem

**Comment by mpygruu** [comment]
+ po navigation pop i spowrotem do settings screen i już wszystkie tłumaczenia są

**Comment by matyjb** [comment]
Dobra mam. Tak jak podejrzewałem chodziło o optymalizacje Fluttera dla widgetów które są const. Widgety const się nie rerenderują, więc stringi w tym widgecie pozostają jakie były.

### Fix:
Jeżeli używamy w danym widgecie .tr() do tłumaczenia to ten widget nie może mieć const konstruktora. Wystarczy go usunąć i już będzie ok.

----------------

Po obiedzie przelecę przez wszystkie widgety i ponaprawiam je.
