### ISSUE TITLE
Overflow w welcome screen

### ISSUE THREAD

**Issue by mpygruu** [SilverNETGroupSGGW/psggw#59]
![IMG_4494](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/12d5112f-cc04-4ae7-abc3-57f87a76e072)

Niby nic wielkiego ale jakbyśmy zmieniali tekst na dłuższy to sie nie zmieści, może warto w welcome screen użyć Spacer() do ułożenia widgetow w kolumnie zamiast SpacedBox()

**Comment by mpygruu** [comment]
urządzenie to iphone 7

**Comment by ThePhaseless** [comment]
@mpygruu zobacz czy dalej na branchu fix-overflow
