### ISSUE TITLE
Niespójność stylów dla switchy

### ISSUE THREAD

**Issue by mpygruu** [SilverNETGroupSGGW/psggw#60]
![IMG_4495](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/57044f89-c960-4761-b51e-51288ea067f3)

W ustawieniach przy wyborze dark mode oraz w "Customization" niespójność stylów dla switchy, jeden jest material a drugi systemowy.

system iOS

**Comment by matyjb** [comment]
Tak jak pisałem w [issue 61](https://github.com/SilverNETGroupSGGW/psggw/issues/61) skupmy się na Materialu, więc pousuwać wszędzie trzeba te **.adaptive(...)** na widgetach
