### ISSUE TITLE
Crash po kliknięciu opcji Language w settings

### ISSUE THREAD

**Issue by mpygruu** [SilverNETGroupSGGW/psggw#61]
![IMG_4496](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/4a9fad7d-38b8-4fa2-9cf6-8c4e4eb789bf)

Apkę crashuje od razu po kliknięciu i przestaje reagować na jakikolwiek input.

system iOS, na Androidzie śmiga jak należy.

**Comment by mpygruu** [comment]
![IMG_4497](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/bcd03a61-7145-4d67-9f46-f0dd72830837)


Generalnie to naprawiłem ale wygląda to tragicznie, zupełnie nie systemowo. Ogólnie takie smaczki jak wybieranie z listy, czy też alerty itd dla systemu iOS są do przemyślenia w całej apce po przestudiowaniu design guidelines.

Na ten moment mam taki pomysł dla zmiany języka, to jest bardzo native: https://developer.apple.com/design/human-interface-guidelines/pop-up-buttons

Pytanie moje to czy narazie olewamy iOS i doprowadzamy tylko Androida do pełnej funkcjonalności, czy próbować na bieżąco wprowadzać native zmiany? @matyjb

**Comment by matyjb** [comment]
Ja bym się skupił na materialu jak na razie, a potem możemy się zająć cupertino. Też bym to zmienił na dropdown'a

**Comment by matyjb** [comment]
Możesz przerobić to

**Comment by mpygruu** [comment]
@matyjb na androidzie też zmienić na dropdown czy zostawiamy alertDialog i zamykamy issue bez wprowadzania zmian do czasu ukończenia material?

**Comment by matyjb** [comment]
Hmm, ten dropdown na materialu trochę wygląda słabo, więc nie wiem czy rezygnować z alerta. Jeżeli masz pomysł jak upiększyć tego materialowego dropdowna to _go ahead_

**Comment by mpygruu** [comment]
Ok, pobawię się i zobaczymy. Najwyżej zamkniemy issue bez wprowadzania zmian

**Comment by mpygruu** [comment]
![Screenshot from 2024-01-14 19-55-08](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/3332239f-9b63-4033-a01f-26af313dc261)

Coś takiego poklikałem ale średnio mi się podoba, alert lepszy

**Comment by matyjb** [comment]
No właśnie też mi się średnio podoba. Niech alert zostanie
