### ISSUE TITLE
PageView.builder i widok planu zajęć

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/psggw#70]
Skoro zajęcia jednak są przypisane do konkretnego dnia to wymyśliłem, żeby nie robić 7 tabów na dni tygodnia tylko nieskończoność tabów dla każdego dnia i do tego posłuży PageView.builder. 

Koncepcja jest taka, że tam gdzie są normalnie Tab'y pod appbarem to dać tam na środku datę, nazwę dnia oraz ikonkę od kalendarza (albo na samo kliknięcie daty) by można sobie było wybrać z calendarpickera dzień. Po bokach dać strzałki by inkrementować/dekrementować dzień. Fajnie by było gdyby data dnia (wraz z nazwą) była na karuzeli i jej animacja była zsynchronizowana z animacją PageView. Tu można chyba rozwiązać to własnym cubitem co będzie nad scaffoldem i BlocListenerami by ustawiać wartości w kontrolerach pageview i karuzeli, ale może jest lepszy sposób.

Do karuzeli można użyć paczki z pub'a np tej [carousel_slider](https://pub.dev/packages/carousel_slider) albo tej [infinite_carousel](https://pub.dev/packages/infinite_carousel)

Jak na razie niech te page'e będą puste.

**Comment by mpygruu** [comment]
Świetny pomysł, coś podobnego jest w apce kalendarza na ios, może jakieś inspiracje z tego wyjdą więc załączam 😎 @matyjb 

![image](https://github.com/SilverNETGroupSGGW/psggw/assets/92801562/13061c20-2760-40d3-9e91-6092d44932c6)

**Comment by matyjb** [comment]
Hmm chyba nawet ten design skopiuje

**Comment by matyjb** [comment]
ale coś trzeba zmienić, żeby apple się nie czepiał xdd
